apiVersion: v1
kind: Service
metadata:
  name: {{ include "Tlaloc.Api.fullname" . }}
  labels:
    {{- include "Tlaloc.Api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetport }}
      nodePort: {{ .Values.service.nodeport }}
    - name: {{ .Values.servicessl.name }}
      port: {{ .Values.servicessl.port }}
      protocol: TCP
      targetPort: {{ .Values.servicessl.targetport }}
      nodePort: {{ .Values.servicessl.nodeport }}
  selector:
    {{- include "Tlaloc.Api.selectorLabels" . | nindent 4 }}
