apiVersion: v1
kind: Service
metadata:
  name: {{ include "balder.fullname" . }}
  labels:
    {{- include "balder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      nodePort: {{ .Values.service.nodeport }}
  selector:
    {{- include "balder.selectorLabels" . | nindent 4 }}
