apiVersion: v1
kind: ConfigMap
metadata:
  name: delta-configurations
data:
  database_database: "database"
  database_hostname: "hostname"
  database_username: "username"
  database_password: "password"
  smtp_server: "smtp.mail.com"
  smtp_port: "587"
  smtp_user: ""
  smtp_password: "pass"
